// copy this file as .config.js to get notifications for preferred cars
// NOTE: also supports multiple preferred car configs, if exported as
// an array of objects instead of an object

module.exports = [
  {
    PREFERRED_price: 41000,
    PREFERRED_model: 'Model Y',
    PREFERRED_year: '>=2021',
    PREFERRED_city: '',
    PREFERRED_state: '',
    PREFERRED_storeName: '',
    PREFERRED_odometer: '<30000',
    PREFERRED_color: 'GRAY',
    PREFERRED_trim: '!Model Y Standard Range Rear-Wheel Drive',
    PREFERRED_transportationFee: undefined,
    PREFERRED_hasFsd: true,
    PREFERRED_hasEap: undefined,
    PREFERRED_hasAccelerationBoost: undefined,
    PREFERRED_hasTowHitch: undefined,
    PREFERRED_interior: 'PREMIUM_BLACK',
    PREFERRED_wasDamaged: false,
    PREFERRED_originalInCustomerGarageDate: undefined,
    PREFERRED_seatLayout: '',
    PREFERRED_vin: '',
    PREFERRED_wheels: '',
  },
  {
    PREFERRED_price: 43000,
    PREFERRED_model: 'Model Y',
    PREFERRED_year: '>=2022',
    PREFERRED_city: '',
    PREFERRED_state: '',
    PREFERRED_storeName: '',
    PREFERRED_odometer: '<30000',
    PREFERRED_color: 'GRAY',
    PREFERRED_trim: '!Model Y Standard Range Rear-Wheel Drive',
    PREFERRED_transportationFee: undefined,
    PREFERRED_hasFsd: true,
    PREFERRED_hasEap: undefined,
    PREFERRED_hasAccelerationBoost: undefined,
    PREFERRED_hasTowHitch: undefined,
    PREFERRED_interior: 'PREMIUM_BLACK',
    PREFERRED_wasDamaged: false,
    PREFERRED_originalInCustomerGarageDate: undefined,
    PREFERRED_seatLayout: '',
    PREFERRED_vin: '',
    PREFERRED_wheels: '',
  },
];
